apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: manix-web
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - app.manix-ai.example.com
      secretName: manix-web-tls
  rules:
    - host: app.manix-ai.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prod-manix-web
                port:
                  number: 3000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: prod-manix-api
                port:
                  number: 3001


