apiVersion: v1
kind: ConfigMap
metadata:
  name: manix-config
data:
  NODE_ENV: "production"
  PORT: "3001"
  NEXT_PUBLIC_API_URL: "http://manix-api:3001"
  NEXT_PUBLIC_WS_URL: "ws://manix-api:3001"


