apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: manix-ai

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment-api.yaml
  - service-api.yaml
  - deployment-web.yaml
  - service-web.yaml
  - statefulset-postgres.yaml
  - service-postgres.yaml
  - statefulset-redis.yaml
  - service-redis.yaml

commonLabels:
  app.kubernetes.io/part-of: manix-ai
  app.kubernetes.io/managed-by: kustomize


