apiVersion: v1
kind: Service
metadata:
  name: manix-web
  labels:
    app.kubernetes.io/name: manix-web
spec:
  selector:
    app.kubernetes.io/name: manix-web
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP


