apiVersion: v1
kind: Service
metadata:
  name: manix-redis
  labels:
    app.kubernetes.io/name: manix-redis
spec:
  selector:
    app.kubernetes.io/name: manix-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  clusterIP: None


