apiVersion: v1
kind: Service
metadata:
  name: manix-postgres
  labels:
    app.kubernetes.io/name: manix-postgres
spec:
  selector:
    app.kubernetes.io/name: manix-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  clusterIP: None


