apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: manix-web
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  rules:
    - host: staging.manix-ai.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stg-manix-web
                port:
                  number: 3000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: stg-manix-api
                port:
                  number: 3001


