apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: manix-ai-staging

resources:
  - ../../base
  - ingress.yaml

namePrefix: stg-

commonLabels:
  environment: staging

patches:
  - target:
      kind: Deployment
      name: manix-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: manix-web
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1


